export const phonebookTypes = {
  FETCH_PHONEBOOK_LIST_START: "FETCH_PHONEBOOK_LIST_START",
  FETCH_PHONEBOOK_LIST_SUCCESS: "FETCH_PHONEBOOK_LIST_SUCCESS",
  FETCH_PHONEBOOK_LIST_FAILURE: "FETCH_PHONEBOOK_LIST_FAILURE",

  FETCH_ADD_PHONEBOOK_LIST_START: "FETCH_ADD_PHONEBOOK_LIST_START",
  FETCH_ADD_PHONEBOOK_LIST_SUCCESS: "FETCH_ADD_PHONEBOOK_LIST_SUCCESS",
  FETCH_ADD_PHONEBOOK_LIST_FAILURE: "FETCH_ADD_PHONEBOOK_LIST_FAILURE",

  FETCH_DELETE_PHONEBOOK_LIST_START: "FETCH_DELETE_PHONEBOOK_LIST_START",
  FETCH_DELETE_PHONEBOOK_LIST_SUCCESS: "FETCH_DELETE_PHONEBOOK_LIST_SUCCESS",
  FETCH_DELETE_PHONEBOOK_LIST_FAILURE: "FETCH_DELETE_PHONEBOOK_LIST_FAILURE",

  FETCH_UPDATE_PHONEBOOK_LIST_START: "FETCH_UPDATE_PHONEBOOK_LIST_START",
  FETCH_UPDATE_PHONEBOOK_LIST_SUCCESS: "FETCH_UPDATE_PHONEBOOK_LIST_SUCCESS",
  FETCH_UPDATE_PHONEBOOK_LIST_FAILURE: "FETCH_UPDATE_PHONEBOOK_LIST_FAILURE",
};
